- hosts: localhost
  tasks:
    - name: Create a custom credential type
      ansible.tower.tower_credential_type:
        tower_host: "{{ tower_host }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        name: Test credential type
        kind: cloud
        state: present
        inputs:
          fields:
            - id: thetoken
              type: string
              label: TOKEN
          required:
            - thetoken
        injectors:
          env:
            TOKEN: '{{ thetoken }}'
