---
- name: This playbook configures hosts created with terraform
  hosts: all
  tasks:
    - name: Ping the host for testing
      ping:

    - name: Display host group names
      debug:
        msg: "This host is in the following groups:  {{ group_names }}"
