---
- name: Display environment variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print environemnt variables
      ansible.builtin.command: /bin/env
      changed_when: false

    - name: Print tower_webhook_payload var
      ansible.builtin.debug:
        var: tower_webhook_payload

    - name: Git commit type
      ansible.builtin.set_fact:
        git_branch_name: "{{ tower_webhook_payload.ref | regex_search('feature\\/.*') }}"
        git_branch_create_event: "{{ tower_webhook_payload.before is regex('^0+$') }}"
        git_branch_delete_event: "{{ tower_webhook_payload.after is regex('^0+$') }}"

    - name: Print branch name
      ansible.builtin.debug:
        msg:
          - "Git branch name: {{ git_branch_name }}"
          - "Branch create event: {{ git_branch_create_event }}"
          - "Branch delete event: {{ git_branch_delete_event }}"

    - block:
        - name: Create a project for the feature branch
          ansible.controller.project:
            name: "LINUX - feature branch {{ git_branch_name }}"
            description: "Test environment for feature branch {{ git_branch_name }}"
            organization: "Test Organization 1"
            scm_type: git
            scm_url: "{{ tower_webhook_payload.repository.git_http_url }}"
            scm_branch: "{{ git_branch_name }}"
      when:
        - not git_branch_delete_event | bool
