---
- name: create terraform user
  user:
    name: "{{ terraform.user }}"
    create_home: yes
    home: /home/terraform
    state: present

- name: clone the given terraform repo
  become: yes
  become_user: terraform
  git:
    repo: "{{ terraform.repo }}"
    update: yes
    dest: /home/terraform/tf
