---
- include_tasks: install.yml

- name: create terraform user
  user:
    name: "{{ terraform.user }}"
    create_home: yes
    home: "{{ terraform.home }}"
    state: present

- name: clone the given terraform repo
  become: yes
  become_user: "{{ terraform.user }}"
  git:
    repo: "{{ terraform.repo }}"
    update: yes
    dest: "{{ terraform.dir }}"

- name: Include terraform setup tasks
  include_tasks: terraform.yml

- name: Include terraform plan tasks
  include_tasks: terraform_plan.yml
  when: plan | bool

- name: Include terraform apply tasks
  include_tasks: terraform_apply.yml
  when: apply | bool
